* ABOUT neon-os

*neon-os* is the name that we have chosen for our pre-installation
script which will deploy our awesome config,qtile config,fish config,
picom config,i3 config,etc to create a proper full-fleged desktop
experiance it is basically our desktop environment on your machine and
is *a distro for any user*.

* preview

** Awesomewm

*** Preview coming Soon

** Qtile (Flagship)

*** Preview coming Soon

** i3wm

*** Preview coming Soon

* NOTE

- neon-os is only for *x86_64 architecture* and will mot work on arm or
any other architectures.

- The installation-script should only be run after the base install in
user mode

* Arch Linux installation recommendations/suggestions

If you want to have increased performance, security and lower power consumption. Take a look at [[file:RECOMMENDTIONS.org][RECOMMENDATIONS.org]].

* prerequisites

Make sure you have installed all of the following prerequisites on your
machine:

1. git

#+begin_src shell

  sudo pacman -S git

#+end_src

2. /root and /home installed on seperate disks (hdd or ssd).

* Installation

#+begin_src shell

    git clone https://gitlab.com/NEON-MMD/neon-os.git
    cd neon-os
    chmod +x neon-os
    ./neon-os

#+end_src

* Contributing

Contributions are welcome. It does not matter who you are you can still contribute to the project in your way :).

** Not a developer but still want to contribute

Here is [[https://youtu.be/FccdqCucVSI][video]] by Mr. Nick on how to contribute and credit to him as well

** Developer

If you are developer, have a look at the [[file:CONTRIBUTING.org][CONTRIBUTING.org]] document for more information.

* advice or suggestions

for any advice or suggestion email us on:

- slenderhacker1234@gmail.com
- mohammed.patel19@vit.edu

* Post-installation

** Todo

- set the theme using lxappearance
- check the aliases to use by running the following command:

#+begin_src shell

  alias

#+end_src

** common issues

* Credits

- Mr.Derek Taylor @gitlab.com/dwt1
- the lain community
- the arch community
- paru aur community
- awesomewm community
- qtile community
- i3 community
- polybar community
